### ISSUE TITLE
SafeArea

### ISSUE THREAD

**Issue by wrteam02** [itsarvinddev/map_location_picker#19]
needed extra optional (top and bottom) parameter for safearea,
its creating problem sometimes in ios,

for example, i want to set false to bottom then there is not any parameter for that, and because of that i face extra bottom space in my UI.

[example1](https://drive.google.com/file/d/1aMT68jkFcDk73jOmXjQVUtL1mxVsVc-S/view?usp=sharing)
[example2](https://drive.google.com/file/d/1lZwNC1tPjRX_vWLXac5BWBaZV57wcxN4/view?usp=sharing)

Thank you

**Comment by itsarvinddev** [comment]
I'm glad this package was useful for you @wrteam02 
You have a good point. I agree. This option will be added in the next release.
