### ISSUE TITLE
Sugestion box background

### ISSUE THREAD

**Issue by DevTiago** [itsarvinddev/map_location_picker#2]
Congrats for the package!

I've tried and it works perfect.. but i have a doubt that i can't figure how to solve: The "sugestion box" keeps under the search bar keeps with a transparency that i can't 'remove'. 

![image](https://user-images.githubusercontent.com/41440390/176133875-09f0ff90-320d-4618-8b49-f83d1dacfa32.png)

How can i define that background color?

**Comment by itsarvinddev** [comment]
Hi @DevTiago, I fix it on the next update, it's coming soon.

**Comment by itsarvinddev** [comment]
- Remake of the entire project form scratch.
- Added new features and UI customizations.
- Added flutter web support.
- https://github.com/rvndsngwn/map_location_picker/issues/2 bug fixed.
- https://github.com/rvndsngwn/map_location_picker/issues/3 bug fixed.
- https://github.com/rvndsngwn/map_location_picker/issues/4 Enhancement has been postponed.
