### ISSUE TITLE
Result is null when current location button is not clicked

### ISSUE THREAD

**Issue by bhaskar8088** [itsarvinddev/map_location_picker#22]
Here is the code I am using:

`    return MapLocationPicker(
      apiKey: "key",
      currentLatLng: location,
      onNext: (GeocodingResult? result) {
        if (result != null) {
          print("result");
          print(result);
        }
      },`

If you see the below image, if I press the round dot icon then if I search for any location in search bar, then its showing the result in onNext. But if I dont press current location icon(round dot icon) and if I search any location in search bar, then its showing the address in the bottom input box but when I click next, onNext is getting result as null. 

![WhatsApp-Image-2023-08-06-at-14-00-49](https://github.com/rvndsngwn/map_location_picker/assets/8342120/4ba21fa8-a2a3-4084-9929-5f1e6aab02da)

I think forcing the user to select current location is not correct. Instead, I want to show the current location automatically. For that, I am using below code:

`  getLocation() async {
    LocationPermission permission;
    permission = await Geolocator.requestPermission();
    Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high);
    setState(() {
      lat = position.latitude;
      lng = position.longitude;
      location = LatLng(lat, lng);
    });
    setState(() {
      _currentPosition = location;
    });
  }`
  
  This way, I am able to show current location when screen is opened, but when next is clicked, onNext is showing result as null when round dot icon is clicked. 
  
  Is there anyway I can auto select current location button or someway so result will not be null when onNext is clicked without user clicking current location button.

Thanks.

**Comment by itsarvinddev** [comment]
Hi @bhaskar8088 I just added this to the package [map_location_picker: ^1.2.5](https://pub.dev/packages/map_location_picker)

**Comment by bhaskar8088** [comment]
@rvndsngwn Thanks, that worked. But there is another issue.

After I search for any address and after pressing next arrow button, it is showing address(with lat, lng) of current location in the onNext function instead of showing the address of the newly searched location. Can you please fix this too? Thanks.

**Comment by atg-anil-ahuja** [comment]
@bhaskar8088 i have fixed this issue in my repo you can use this repo https://github.com/atg-anil-ahuja/map_location_picker.git and modify your pubspec.yaml file.
map_location_picker: 
    git:
      url: https://github.com/atg-anil-ahuja/map_location_picker.git
      ref: master

**Comment by itsarvinddev** [comment]
Hi @bhaskar8088 the has been resolved
