### ISSUE TITLE
After import  Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker_bdaya/src/datetime_picker_theme.dart'.

### ISSUE THREAD

**Issue by tnssuet** [itsarvinddev/map_location_picker#23]
/C:/Users/TaimoorNazir/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_datetime_picker_bdaya-2.0.0/lib/flutter_datetime_picker_bdaya.dart:7:1: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker_bdaya/src/datetime_picker_theme.dart'.
import 'src/datetime_picker_theme.dart';
^^^^^^^^^^^^^^^
/C:/Users/TaimoorNazir/AppData/Local/Pub/Cache/hosted/pub.dev/form_builder_extra_fields-8.5.0/lib/src/fields/form_builder_cupertino_date_time_picker.dart:6:1: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker_bdaya/src/datetime_picker_theme.dart'.
import 'package:flutter_datetime_picker_bdaya/flutter_datetime_picker_bdaya.dart';
^^^^^^^^^^^^^^^
/C:/Users/TaimoorNazir/AppData/Local/Pub/Cache/hosted/pub.dev/form_builder_extra_fields-8.5.0/lib/src/widgets/flutter_chips_input/chips_input.dart:87:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.insertContent
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1117:8: Context: 'TextInputClient.insertContent' is defined here.
  void insertContent(KeyboardInsertedContent content) {}
       ^^^^^^^^^^^^^
/C:/Users/TaimoorNazir/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_datetime_picker_bdaya-2.0.0/lib/flutter_datetime_picker_bdaya.dart:200:31: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker_bdaya/src/datetime_picker_theme.dart'.
        this.theme = theme ?? DatePickerTheme(),
                              ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by tnssuet** [comment]
name: abc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.1.0
  http: ^0.13.5
  flutter_chips_input: ^1.9.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  camera: ^0.10.3
  video_player: ^2.5.1
  image_picker: ^0.8.6+1
  path_provider: ^2.0.12
  geolocator: ^9.0.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  image_gallery_saver: '^1.7.1'
  intl: ^0.17.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  google_place:
  map_location_picker: ^1.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: 
  build_runner: 
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Barlow-Light
      fonts:
        - asset: assets/fonts/Barlow-Light.ttf

    - family: Barlow-Medium
      fonts:
        - asset: assets/fonts/Barlow-Medium.ttf

    - family: Barlow-Regular
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf

**Comment by itsarvinddev** [comment]
Hi @tnssuet 

Update the package `map_location_picker: ^1.1.0` to `map_location_picker: ^1.2.5` latest updated version. After the update, I hope this issue has been resolved.

Feel free to let me know whether it works.

**Comment by tnssuet** [comment]
After update to version  ^1.2.5 i have received below error 
Because map_location_picker >=1.2.2 depends on http ^1.1.0 and testproject depends on http ^0.13.5, map_location_picker
  >=1.2.2 is forbidden.
So, because testproject depends on map_location_picker ^1.2.5, version solving failed.

**Comment by tnssuet** [comment]
@rvndsngwn

**Comment by tnssuet** [comment]
Yes after updating other versions of packages issue is resolved 


Thanks
