### ISSUE TITLE
App Crash when poping from Google map location picker

### ISSUE THREAD

**Issue by appa204544** [itsarvinddev/map_location_picker#29]
https://github.com/rvndsngwn/map_location_picker/assets/64253940/1acd6f44-63c0-46dd-b813-2827a1afdba7

Getting Crash when back from Google map.
Flutter Version - 3.7.3

I have tried with latest map_picker_flutter version and flutter 3.13.2, but still getting the crash.

**Comment by itsarvinddev** [comment]
Hi @appa204544 let me check this and updating soon
