### ISSUE TITLE
More languages support / handle no language support

### ISSUE THREAD

**Issue by Lampat** [itsarvinddev/map_location_picker#4]
My app uses 2 languages, english and greek, when the phone is on greek the package doesn't work correctly, apparently greek language is not supported by the package and the top bar is a red box.. 

Either it should have more languages to support or have a fallback that if it doesn't find the device's language to get a default (eg english
![Screenshot_1](https://user-images.githubusercontent.com/26882589/177322495-2407ee0e-a197-47e8-83d6-10807b522b54.png)
)

**Comment by Lampat** [comment]
Since I forgot this is what it shows in the debug console
════════ Exception caught by widgets library ═══════════════════════════════════
No instance of S present in the widget tree. Did you add S.delegate in localizationsDelegates?
'package:map_location_picker/generated/l10n.dart':
package:map_location_picker/generated/l10n.dart:1
Failed assertion: line 44 pos 12: 'instance != null'


And in my main class
locale: localeManager.locale,
supportedLocales: AppService().locales(),
localizationsDelegates: const [
  S.delegate,
  AppLocalizations.delegate,
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
  GlobalCupertinoLocalizations.delegate,
],

**Comment by itsarvinddev** [comment]
Hi @Lampat, I would love it if you translate intl_es.arb into the Greek language.

Also, I fix this error.

```
{
  "@@locale": "en",
  "please_check_your_connection": "Please check your connection",
  "server_error": "Server error",
  "access_to_location_denied": "Access to location denied",
  "allow_access_to_the_location_services": "Allow access to the location services.",
  "access_to_location_permanently_denied": "Access to location permanently denied",
  "allow_access_to_the_location_services_from_settings": "Allow access to the location services for this App using the device settings.",
  "ok": "Ok",
  "cant_get_current_location": "Can't get current location",
  "please_make_sure_you_enable_gps_and_try_again": "Please make sure you enable GPS and try again",
  "search_place": "Search place",
  "finding_place": "Finding place...",
  "no_result_found": "No result found",
  "unnamedPlace": "Unnamed place"
}
```

**Comment by Lampat** [comment]
Hi again @rvndsngwn , is this what you meant??
{
  "@@locale": "el",
  "please_check_your_connection": "Παρακαλώ ελέγξτε τη συνδεσή σας",
  "server_error": "Σφάλμα διακομιστή",
  "access_to_location_denied": "Δεν επιτρέπεται η πρόβαση στην τοποθεσία",
  "allow_access_to_the_location_services": "Επιτρέψτε την πρόσβαση στις υπηρεσίες της τοποθεσίας.",
  "access_to_location_permanently_denied": "Απαγορεύεται οριστικά η πρόσβαση στην τοποθεσία της συσκευής",
  "allow_access_to_the_location_services_from_settings": "Επιτρέψτε την πρόσβαση στις υπηρεσίες τοποθεσίας για αυτήν την εφαρμογή χρησιμοποιώντας τις ρυθμίσεις της συσκευής.",
  "ok": "Οκ",
  "cant_get_current_location": "Δεν είναι δυνατή η λήψη της τρέχουσας τοποθεσίας",
  "please_make_sure_you_enable_gps_and_try_again": "Βεβαιωθείτε ότι έχετε ενεργοποιήσει το GPS και δοκιμάστε ξανά",
  "search_place": "Αναζήτηση τοποθεσίας",
  "finding_place": "Εύρεση τοποθεσίας...",
  "no_result_found": "Δεν βρέθηκε αποτέλεσμα",
  "unnamedPlace": "Τοποθεσία χωρίς όνομα"
}

**Comment by itsarvinddev** [comment]
- Remake of the entire project form scratch.
- Added new features and UI customizations.
- Added flutter web support.
- https://github.com/rvndsngwn/map_location_picker/issues/2 bug fixed.
- https://github.com/rvndsngwn/map_location_picker/issues/3 bug fixed.
- https://github.com/rvndsngwn/map_location_picker/issues/4 Enhancement has been postponed.
