### ISSUE TITLE
Cannot select a location directly after searching in the search bar

### ISSUE THREAD

**Issue by glupeksha** [itsarvinddev/map_location_picker#5]
E/flutter (12031): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field '_geocodingResult@1248352992' has not been initialized.
E/flutter (12031): #0      _MapLocationPickerState._geocodingResult (package:map_location_picker/src/map_location_picker.dart)
E/flutter (12031): #1      _MapLocationPickerState.build.<anonymous closure> (package:map_location_picker/src/map_location_picker.dart:502:48)
E/flutter (12031): #2      _MapLocationPickerState.build.<anonymous closure> (package:map_location_picker/src/map_location_picker.dart:501:38)
E/flutter (12031): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
E/flutter (12031): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (12031): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
E/flutter (12031): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
E/flutter (12031): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
E/flutter (12031): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (12031): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
E/flutter (12031): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
E/flutter (12031): #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
E/flutter (12031): #12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
E/flutter (12031): #13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
E/flutter (12031): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
E/flutter (12031): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
E/flutter (12031): #16     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (12031): #17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (12031): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (12031): #19     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (12031): #20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (12031): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
E/flutter (12031):

**Comment by itsarvinddev** [comment]
let me check

**Comment by itsarvinddev** [comment]
resolved in [1.0.1](https://pub.dev/packages/map_location_picker)
