### ISSUE TITLE
LateInitializationError on _geocodingresult

### ISSUE THREAD

**Issue by stha-ums** [itsarvinddev/map_location_picker#6]
`E/flutter (16095): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field '_geocodingResult@1800352992' has not been initialized.
E/flutter (16095): #0      _MapLocationPickerState._geocodingResult (package:map_location_picker/src/map_location_picker.dart)
package:map_location_picker/src/map_location_picker.dart:1
E/flutter (16095): #1      _MapLocationPickerState.build.<anonymous closure>
package:map_location_picker/src/map_location_picker.dart:502
E/flutter (16095): #2      _MapLocationPickerState.build.<anonymous closure>
package:map_location_picker/src/map_location_picker.dart:501
E/flutter (16095): #3      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:1005
E/flutter (16095): #4      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:198
E/flutter (16095): #5      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:613
E/flutter (16095): #6      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:298
E/flutter (16095): #7      BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:269
E/flutter (16095): #8      GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
E/flutter (16095): #9      GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:449
E/flutter (16095): #10     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:425
E/flutter (16095): #11     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:329
E/flutter (16095): #12     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:380
E/flutter (16095): #13     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:344
E/flutter (16095): #14     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:302
E/flutter (16095): #15     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:285
E/flutter (16095): #16     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (16095): #17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (16095): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (16095): #19     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (16095): #20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (16095): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)`

![image](https://user-images.githubusercontent.com/34161121/181712798-ec65f816-5c24-4890-a567-c2774a54eb29.png)

![image](https://user-images.githubusercontent.com/34161121/181712839-eccfd6f7-0cfd-4178-8d58-970926ae3a00.png)

this exception is thrown if the user doesn't select any location and clicks next. 
the solution might be to remove late from _geocodingResult since it's already nullable. 

or not displaying the next button until there is location loaded.

**Comment by stha-ums** [comment]
#5  same as this one.

**Comment by itsarvinddev** [comment]
resolved in [1.0.1](https://pub.dev/packages/map_location_picker)
